services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: clips:${CLIPS_VERSION:-latest}
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v2.48.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - api

  grafana:
    image: grafana/grafana:10.2.2
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus

volumes:
  prometheus-data:
    name: prometheus-data
  grafana-data:
    name: grafana-data
